name: "GitHub Classroom Autograding Baygon Handler"
description: "Notify GitHub Classroom with the tests results"
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default,
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository.
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  report:
    description: 'Bagon report (json)'
    default: 'baygon-report.json'
runs:
  using: "node20"
  main: "dist/main.js"
