name: Autograding Tests
"on":
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install and build node assets
        run: |
          npm install --silent
          npm run build
      - name: Autograding Reporter
        uses: ./
